### ISSUE TITLE
WindowsSever2019上增加屏幕的时候报错

### ISSUE THREAD

**Issue by Pansvfj** [fufesou/RustDeskIddDriver#11]
![image](https://github.com/fufesou/RustDeskIddDriver/assets/42718287/ca888d5e-7928-4f61-a999-eb45d5cb3057)

**Comment by fufesou** [comment]
Sorry for late.

0x103 means no more data, it seems you did not install the driver.

Please try input "c" --> "i" --> "a"

If you find other errors, please provide screenshots as well.

**Comment by Pansvfj** [comment]
I'm sure I installed the driver, In the device manager, I saw the driver on the display adapter, but there is a yellow exclamation point, so this function returns 0x103. I guess this version of windows server needs special treatment?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月22日(周五) 晚上7:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fufesou/RustDeskIddDriver] WindowsSever2019上增加屏幕的时候报错 (Issue #11)




 
Sorry for late.
 
0x103 means no more data, it seems you did not install the driver.
 
Please try input "c" --&gt; "i" --&gt; "a"
 
If you find other errors, please provide screenshots as well.

**Comment by fufesou** [comment]
So you failed to install the driver.

Can you give me a screenshot of the error message?
Or you can check the driver in Device Manager to see more details.

**Comment by Pansvfj** [comment]
Hello, there are screenshots about these issues.
![image](https://github.com/fufesou/RustDeskIddDriver/assets/42718287/fca01c9c-8681-4316-80e3-13a4559272ce)
![image](https://github.com/fufesou/RustDeskIddDriver/assets/42718287/dfd7aeb5-166a-4b5a-8f81-14ceb567aa05)

**Comment by Pansvfj** [comment]
This is my OS version:
![image](https://github.com/fufesou/RustDeskIddDriver/assets/42718287/998f6f83-a46f-464b-b3a6-2e8a19fb3289)

**Comment by fufesou** [comment]
Maybe the same issue. Can you please check the system event log?

https://github.com/rustdesk/rustdesk/issues/6280#issuecomment-1793357170

https://github.com/rustdesk/rustdesk/issues/6280#issuecomment-1811837907

https://github.com/rustdesk/rustdesk/issues/6280#issuecomment-1812509692


The UMDF version is defined here https://github.com/fufesou/RustDeskIddDriver/blob/62b04e729e770b17ed6ebd4eaaa901a63d3475e4/RustDeskIddDriver/RustDeskIddDriver.vcxproj#L101

You can change it to a lower version.


But as https://github.com/rustdesk/rustdesk/issues/6280#issuecomment-1812509692 stated,

> But [IddCxAdapterInitAsync](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/nf-iddcx-iddcxadapterinitasync) is not supported on Windows 1809.
RustDeskIdd still does not work since monitors cannot be plug in.

**Comment by fufesou** [comment]
If you don't need plug-and-play functionality, you can try another idd.

https://github.com/itsmikethetech/Virtual-Display-Driver

**Comment by Pansvfj** [comment]
You are right, Thank you very much!
